import { useState } from 'react'

const DEMO_RECIPIENT = 'dianak@mcmaster.ca'
const ORGANIZATIONS = [
  'North Industrial Plant',
  'Central Processing Facility',
  'Hamilton Waterworks',
  'McMaster Facilities',
]

export default function AdvisoryPresentation() {
  const [subject, setSubject] = useState('')
  const [organization, setOrganization] = useState('')
  const [message, setMessage] = useState('')
  const [feedback, setFeedback] = useState('')

  function handleSubmit(event) {
    event.preventDefault()
    setFeedback('')

    const trimmedSubject = subject.trim()
    const trimmedMessage = message.trim()
    if (!organization || !trimmedSubject || !trimmedMessage) {
      setFeedback('Please fill out organization, subject, and message.')
      return
    }

    const emailSubject = `[SCEMAS Advisory] ${organization}: ${trimmedSubject}`
    const emailBody = [
      `Organization: ${organization}`,
      '',
      trimmedMessage,
      '',
      '(Generated by SCEMAS advisory demo form)',
    ].join('\n')

    // Barebones demo: uses the user's default mail client, no backend/service.
    window.location.href = `mailto:${DEMO_RECIPIENT}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`
    setFeedback(`Draft opened to ${DEMO_RECIPIENT}.`)
  }

  return (
    <section className="page-shell">
      <h2>Advisory Form</h2>
      <p className="muted-copy">
        Demo mode: this form opens your email app and drafts a message to {DEMO_RECIPIENT}.
      </p>

      <form className="auth-form" onSubmit={handleSubmit}>
        <label className="auth-field">
          <span className="auth-field__label">Organization</span>
          <select value={organization} onChange={(event) => setOrganization(event.target.value)}>
            <option value="">Select an organization</option>
            {ORGANIZATIONS.map((org) => (
              <option key={org} value={org}>
                {org}
              </option>
            ))}
          </select>
        </label>

        <label className="auth-field">
          <span className="auth-field__label">Subject</span>
          <input value={subject} onChange={(event) => setSubject(event.target.value)} />
        </label>

        <label className="auth-field">
          <span className="auth-field__label">Message</span>
          <textarea rows={6} value={message} onChange={(event) => setMessage(event.target.value)} />
        </label>

        <button type="submit" className="action-button">
          Send Advisory Email
        </button>
      </form>

      {feedback ? <p className="muted-copy" style={{ marginTop: 12 }}>{feedback}</p> : null}
    </section>
  )
}